#!/usr/bin/env sh
set -eu
# Make sure containerd snapshotter is active.
if ! docker info --format '{{range .DriverStatus}}{{index . 1}}{{end}}' | grep -q "io.containerd.snapshotter.v1"; then
    echo "Please enable 'Use containerd for pulling and storing images' in Docker Desktop settings first."
    exit 1
fi
# Make sure swarm mode is active.
if [ "$(docker info --format '{{.Swarm.LocalNodeState}}')" = "active" ]; then
    echo "Swarm mode already active"
else
    docker swarm init > /dev/null
    echo "Swarm mode enabled"
fi
# Install the rig command globally.
deno task install
# Build and deploy Caddy.
cd caddy
rig build
rig deploy
printf '\nCaddy is now up-and-running, ready to be configured.\n'
cd ..
# Initialize Caddy config for rig deployments.
rig caddy init
# Trust Caddy's root CA certificate.
rig caddy trust
